// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220416040855_firstcreate")]
    partial class firstcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Domain.Provider", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("gId")
                        .HasColumnType("TEXT");

                    b.Property<int>("sure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("zorluk")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Providers");
                });
#pragma warning restore 612, 618
        }
    }
}
